-- KNBS enhanced realistic synthetic dataset (large)
-- Generated: 2025-10-29T11:45:15.730223Z
-- Counties and subcounties are real administrative names (public sources). Microdata is synthetic.

CREATE DATABASE IF NOT EXISTS knbs_enhanced;
USE knbs_enhanced;

CREATE TABLE counties (county_id INT PRIMARY KEY, county_name VARCHAR(150)) ENGINE=InnoDB;
CREATE TABLE subcounties (subcounty_id INT PRIMARY KEY, county_id INT, subcounty_name VARCHAR(200), FOREIGN KEY (county_id) REFERENCES counties(county_id)) ENGINE=InnoDB;
CREATE TABLE households (household_id INT PRIMARY KEY, county_id INT, subcounty_id INT, location VARCHAR(255), head_age INT, head_gender CHAR(1), num_members INT, income_band VARCHAR(30), energy_source VARCHAR(50), water_source VARCHAR(50), toilet_type VARCHAR(50), FOREIGN KEY (county_id) REFERENCES counties(county_id), FOREIGN KEY (subcounty_id) REFERENCES subcounties(subcounty_id)) ENGINE=InnoDB;
CREATE TABLE persons (person_id INT PRIMARY KEY, household_id INT, age INT, gender CHAR(1), relation_to_head VARCHAR(50), education_level VARCHAR(50), employment_status VARCHAR(50), occupation_code VARCHAR(20), monthly_income_kes INT, FOREIGN KEY (household_id) REFERENCES households(household_id)) ENGINE=InnoDB;
CREATE TABLE businesses (business_id INT PRIMARY KEY, county_id INT, business_name VARCHAR(255), business_type VARCHAR(80), employees INT, revenue_band VARCHAR(50), established_year INT, FOREIGN KEY (county_id) REFERENCES counties(county_id)) ENGINE=InnoDB;
CREATE TABLE schools (school_id INT PRIMARY KEY, county_id INT, subcounty_id INT, school_name VARCHAR(255), level VARCHAR(50), enrolment INT, FOREIGN KEY (county_id) REFERENCES counties(county_id), FOREIGN KEY (subcounty_id) REFERENCES subcounties(subcounty_id)) ENGINE=InnoDB;
CREATE TABLE health_facilities (facility_id INT PRIMARY KEY, county_id INT, subcounty_id INT, facility_name VARCHAR(255), facility_type VARCHAR(80), bed_capacity INT, FOREIGN KEY (county_id) REFERENCES counties(county_id), FOREIGN KEY (subcounty_id) REFERENCES subcounties(subcounty_id)) ENGINE=InnoDB;
CREATE TABLE infrastructure_projects (project_id INT PRIMARY KEY, county_id INT, project_name VARCHAR(255), project_type VARCHAR(80), start_year INT, completion_status VARCHAR(50), FOREIGN KEY (county_id) REFERENCES counties(county_id)) ENGINE=InnoDB;
-- Use LOAD DATA INFILE to import large CSVs for speed.
INSERT INTO counties (county_id, county_name) VALUES (1, 'Baringo');
INSERT INTO counties (county_id, county_name) VALUES (2, 'Bomet');
INSERT INTO counties (county_id, county_name) VALUES (3, 'Bungoma');
INSERT INTO counties (county_id, county_name) VALUES (4, 'Busia');
INSERT INTO counties (county_id, county_name) VALUES (5, 'Elgeyo-Marakwet');
INSERT INTO counties (county_id, county_name) VALUES (6, 'Embu');
INSERT INTO counties (county_id, county_name) VALUES (7, 'Garissa');
INSERT INTO counties (county_id, county_name) VALUES (8, 'Homa Bay');
INSERT INTO counties (county_id, county_name) VALUES (9, 'Isiolo');
INSERT INTO counties (county_id, county_name) VALUES (10, 'Kajiado');
INSERT INTO counties (county_id, county_name) VALUES (11, 'Kakamega');
INSERT INTO counties (county_id, county_name) VALUES (12, 'Kericho');
INSERT INTO counties (county_id, county_name) VALUES (13, 'Kiambu');
INSERT INTO counties (county_id, county_name) VALUES (14, 'Kilifi');
INSERT INTO counties (county_id, county_name) VALUES (15, 'Kirinyaga');
INSERT INTO counties (county_id, county_name) VALUES (16, 'Kisii');
INSERT INTO counties (county_id, county_name) VALUES (17, 'Kisumu');
INSERT INTO counties (county_id, county_name) VALUES (18, 'Kitui');
INSERT INTO counties (county_id, county_name) VALUES (19, 'Kwale');
INSERT INTO counties (county_id, county_name) VALUES (20, 'Laikipia');
INSERT INTO counties (county_id, county_name) VALUES (21, 'Lamu');
INSERT INTO counties (county_id, county_name) VALUES (22, 'Machakos');
INSERT INTO counties (county_id, county_name) VALUES (23, 'Makueni');
INSERT INTO counties (county_id, county_name) VALUES (24, 'Mandera');
INSERT INTO counties (county_id, county_name) VALUES (25, 'Marsabit');
INSERT INTO counties (county_id, county_name) VALUES (26, 'Meru');
INSERT INTO counties (county_id, county_name) VALUES (27, 'Migori');
INSERT INTO counties (county_id, county_name) VALUES (28, 'Mombasa');
INSERT INTO counties (county_id, county_name) VALUES (29, 'Murang''a');
INSERT INTO counties (county_id, county_name) VALUES (30, 'Nairobi');
INSERT INTO counties (county_id, county_name) VALUES (31, 'Nakuru');
INSERT INTO counties (county_id, county_name) VALUES (32, 'Nandi');
INSERT INTO counties (county_id, county_name) VALUES (33, 'Narok');
INSERT INTO counties (county_id, county_name) VALUES (34, 'Nyamira');
INSERT INTO counties (county_id, county_name) VALUES (35, 'Nyandarua');
INSERT INTO counties (county_id, county_name) VALUES (36, 'Nyeri');
INSERT INTO counties (county_id, county_name) VALUES (37, 'Samburu');
INSERT INTO counties (county_id, county_name) VALUES (38, 'Siaya');
INSERT INTO counties (county_id, county_name) VALUES (39, 'Taita-Taveta');
INSERT INTO counties (county_id, county_name) VALUES (40, 'Tana River');
INSERT INTO counties (county_id, county_name) VALUES (41, 'Tharaka-Nithi');
INSERT INTO counties (county_id, county_name) VALUES (42, 'Trans-Nzoia');
INSERT INTO counties (county_id, county_name) VALUES (43, 'Turkana');
INSERT INTO counties (county_id, county_name) VALUES (44, 'Uasin Gishu');
INSERT INTO counties (county_id, county_name) VALUES (45, 'Vihiga');
INSERT INTO counties (county_id, county_name) VALUES (46, 'Wajir');
INSERT INTO counties (county_id, county_name) VALUES (47, 'West Pokot');

INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (1, 1, 'Baringo central');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (2, 1, 'Baringo north');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (3, 1, 'Baringo south');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (4, 1, 'Eldama ravine');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (5, 1, 'Mogotio');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (6, 1, 'Tiaty');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (7, 2, 'Bomet central');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (8, 2, 'Bomet east');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (9, 2, 'Chepalungu');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (10, 2, 'Konoin');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (11, 2, 'Sotik');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (12, 3, 'Bumula');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (13, 3, 'Kabuchai');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (14, 3, 'Kanduyi');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (15, 3, 'Kimilil');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (16, 3, 'Mt Elgon');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (17, 3, 'Sirisia');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (18, 3, 'Tongaren');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (19, 3, 'Webuye east');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (20, 3, 'Webuye west');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (21, 4, 'Budalangi');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (22, 4, 'Butula');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (23, 4, 'Funyula');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (24, 4, 'Nambele');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (25, 4, 'Teso North');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (26, 4, 'Teso South');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (27, 5, 'Keiyo north');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (28, 5, 'Keiyo south');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (29, 5, 'Marakwet east');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (30, 5, 'Marakwet west');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (31, 6, 'Manyatta');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (32, 6, 'Mbeere north');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (33, 6, 'Mbeere south');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (34, 6, 'Runyenjes');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (35, 7, 'Daadab');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (36, 7, 'Fafi');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (37, 7, 'Garissa');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (38, 7, 'Hulugho');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (39, 7, 'Ijara');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (40, 7, 'Lagdera balambala');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (41, 8, 'Homabay town');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (42, 8, 'Kabondo');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (43, 8, 'Karachwonyo');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (44, 8, 'Kasipul');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (45, 8, 'Mbita');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (46, 8, 'Ndhiwa');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (47, 8, 'Rangwe');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (48, 8, 'Suba');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (49, 9, 'Isiolo');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (50, 9, 'Garba tula');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (51, 9, 'Merit');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (52, 10, 'Isinya');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (53, 10, 'Kajiado Central');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (54, 10, 'Kajiado North');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (55, 10, 'Loitokitok');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (56, 10, 'Mashuuru');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (57, 11, 'Butere');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (58, 11, 'Kakamega central');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (59, 11, 'Kakamega east');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (60, 11, 'Kakamega north');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (61, 11, 'Kakamega south');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (62, 11, 'Khwisero');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (63, 11, 'Lugari');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (64, 11, 'Lukuyani');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (65, 11, 'Lurambi');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (66, 11, 'Matete');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (67, 11, 'Mumias');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (68, 11, 'Mutungu');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (69, 11, 'Navakholo');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (70, 12, 'Ainamoi');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (71, 12, 'Belgut');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (72, 12, 'Bureti');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (73, 12, 'Kipkelion east');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (74, 12, 'Kipkelion west');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (75, 12, 'Soin sigowet');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (76, 13, 'Gatundu north');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (77, 13, 'Gatundu south');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (78, 13, 'Githunguri');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (79, 13, 'Juja');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (80, 13, 'Kabete');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (81, 13, 'Kiambaa');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (82, 13, 'Kiambu');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (83, 13, 'Kikuyu');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (84, 13, 'Limuru');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (85, 13, 'Ruiru');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (86, 13, 'Thika town');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (87, 13, 'Lari');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (88, 14, 'Ganze');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (89, 14, 'Kaloleni');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (90, 14, 'Kilifi north');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (91, 14, 'Kilifi south');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (92, 14, 'Magarini');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (93, 14, 'Malindi');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (94, 14, 'Rabai');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (95, 15, 'Kirinyaga central');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (96, 15, 'Kirinyaga east');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (97, 15, 'Kirinyaga west');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (98, 15, 'Mwea east');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (99, 15, 'Mwea west');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (100, 16, 'Bobasi');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (101, 16, 'Bomachoge borabu');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (102, 16, 'Bomachoge chache');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (103, 16, 'Boreti');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (104, 16, 'Nyaribari chache');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (105, 16, 'Nyaribari masaba');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (106, 16, 'Gucha west');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (107, 16, 'Gucha south');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (108, 17, 'Kisumu central');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (109, 17, 'Kisumu east');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (110, 17, 'Kisumu west');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (111, 17, 'Mohoroni');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (112, 17, 'Nyakach');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (113, 17, 'Nyando');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (114, 17, 'Seme');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (115, 18, 'Ikutha');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (116, 18, 'Katulani');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (117, 18, 'Kisasi');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (118, 18, 'Kitui central');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (119, 18, 'Kitui west');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (120, 18, 'Lower yatta');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (121, 18, 'Matiyani');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (122, 18, 'Migwani');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (123, 18, 'Mutitu');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (124, 18, 'Mutomo');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (125, 18, 'Muumonikyusu');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (126, 18, 'Mwingi central');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (127, 18, 'Mwingi east');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (128, 18, 'Nzambani');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (129, 18, 'Tseikuru');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (130, 19, 'Kinango');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (131, 19, 'Lungalunga');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (132, 19, 'Msambweni');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (133, 19, 'Mutuga');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (134, 20, 'Laikipia central');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (135, 20, 'Laikipia east');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (136, 20, 'Laikipia north');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (137, 20, 'Laikipia west');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (138, 20, 'Nyahururu');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (139, 21, 'Lamu East');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (140, 21, 'Lamu West');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (141, 22, 'Kathiani');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (142, 22, 'Machakos town');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (143, 22, 'Masinga');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (144, 22, 'Matungulu');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (145, 22, 'Mavoko');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (146, 22, 'Mwala');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (147, 22, 'Yatta');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (148, 23, 'Kaiti');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (149, 23, 'Kibwezi west');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (150, 23, 'Kibwezi east');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (151, 23, 'Kilome');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (152, 23, 'Makueni');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (153, 23, 'Mbooni');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (154, 24, 'Banissa');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (155, 24, 'Lafey');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (156, 24, 'Mandera East');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (157, 24, 'Mandera North');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (158, 24, 'Mandera South');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (159, 24, 'Mandera West');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (160, 25, 'Laisamis');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (161, 25, 'Moyale');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (162, 25, 'North hor');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (163, 25, 'Saku');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (164, 26, 'Buuri');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (165, 26, 'Igembe central');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (166, 26, 'Igembe north');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (167, 26, 'Igembe south');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (168, 26, 'Imenti central');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (169, 26, 'Imenti north');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (170, 26, 'Imenti south');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (171, 26, 'Tigania east');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (172, 26, 'Tigania west');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (173, 27, 'Awendo');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (174, 27, 'Kuria east');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (175, 27, 'Kuria west');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (176, 27, 'Nyatike');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (177, 27, 'Rongo');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (178, 27, 'Suna east');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (179, 27, 'Suna west');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (180, 28, 'Jomvu');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (181, 28, 'Kisauni');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (182, 28, 'Likoni');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (183, 28, 'Mvita');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (184, 28, 'Nyali');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (185, 29, 'Gatanga');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (186, 29, 'Kandara');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (187, 29, 'Kiharu');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (188, 29, 'Kigumo');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (189, 29, 'Kandara');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (190, 30, 'Dagoretti North');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (191, 30, 'Dagoretti South');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (192, 30, 'Embakasi Central');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (193, 30, 'Embakasi East');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (194, 30, 'Embakasi North');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (195, 30, 'Embakasi South');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (196, 30, 'Embakasi West');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (197, 30, 'Lang''ata');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (198, 30, 'Roysambu');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (199, 30, 'Ruaraka');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (200, 30, 'Starehe');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (201, 30, 'Westlands');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (202, 30, 'Kibra');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (203, 30, 'Kamukunji');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (204, 30, 'Makadara');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (205, 30, 'Mathare');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (206, 30, 'Kasarani');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (207, 30, 'Njiru');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (208, 31, 'Bahati');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (209, 31, 'Gilgil');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (210, 31, 'Kuresoi north');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (211, 31, 'Kuresoi south');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (212, 31, 'Molo');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (213, 31, 'Nakuru east');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (214, 31, 'Nakuru north');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (215, 31, 'Nakuru west');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (216, 31, 'Subukia');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (217, 31, 'Rongai');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (218, 32, 'Aldai');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (219, 32, 'Chesumei');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (220, 32, 'Emgwen');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (221, 32, 'Tinderet');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (222, 32, 'Nandi hills');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (223, 33, 'Kilgoris');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (224, 33, 'Narok east');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (225, 33, 'Narok north');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (226, 33, 'Narok south');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (227, 33, 'Narok west');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (228, 33, 'Emurua Dikirr');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (229, 34, 'Borabu');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (230, 34, 'Nyamira North');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (231, 34, 'Nyamira South');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (232, 34, 'West Mugirango');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (233, 35, 'Kinangop');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (234, 35, 'Kipipiri');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (235, 35, 'Mihariga');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (236, 35, 'Ol Kalou');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (237, 35, 'Ol Jorok');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (238, 36, 'Kieni east');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (239, 36, 'Kieni west');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (240, 36, 'Mathira');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (241, 36, 'Othaya');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (242, 36, 'Tetu');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (243, 37, 'Samburu east');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (244, 37, 'Samburu north');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (245, 37, 'Samburu west');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (246, 38, 'Alego Usonga');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (247, 38, 'Bondo');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (248, 38, 'Rarieda');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (249, 38, 'Ugunja');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (250, 38, 'Ugenya');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (251, 38, 'Gem');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (252, 39, 'Taveta');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (253, 39, 'Taita');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (254, 39, 'Voi');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (255, 40, 'Bura');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (256, 40, 'Garsen');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (257, 40, 'Galole');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (258, 40, 'Hulugho');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (259, 41, 'Chuka');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (260, 41, 'Maara');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (261, 41, 'Tharaka');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (262, 42, 'Kwanza');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (263, 42, 'Kiminini');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (264, 42, 'Saboti');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (265, 42, 'Endebess');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (266, 42, 'Cherangany');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (267, 43, 'Loima');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (268, 43, 'Turkana central');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (269, 43, 'Turkana north');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (270, 43, 'Turkana south');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (271, 43, 'Turkana west');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (272, 43, 'Turkana east');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (273, 44, 'Soy');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (274, 44, 'Turbo');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (275, 44, 'Kapseret');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (276, 44, 'Kesses');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (277, 45, 'Emuhaya');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (278, 45, 'Luanda');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (279, 45, 'Vihiga');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (280, 45, 'Hamisi');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (281, 45, 'Sabatia');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (282, 46, 'Wajir east');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (283, 46, 'Wajir north');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (284, 46, 'Wajir south');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (285, 46, 'Wajir west');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (286, 46, 'Wajir central');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (287, 47, 'Kacheliba');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (288, 47, 'Kapenguria');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (289, 47, 'Soi');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (290, 47, 'Sigor');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (291, 47, 'Selupwa');
INSERT INTO subcounties (subcounty_id, county_id, subcounty_name) VALUES (292, 47, 'Pokot south');
